---
- hosts: all
  become: yes
  tasks:

  - name: Install provisioners
    apt: name={{ item }} state=present
    with_items:
    - puppet
    - chef

  - name: Vagrant insecure key
    authorized_key: user=vagrant key=https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub

  - name: Insert "UseDNS no" into sshd_config
    blockinfile:
      dest: /etc/ssh/sshd_config
      block: |
        UseDNS no
